name: Docker Image Build & Push
on:
  create:
    tags: '*'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - run: yarn
      - uses: mr-smithers-excellent/docker-build-push@v1.0
        with:
          image: dsp
          registry: 590877988961.dkr.ecr.eu-north-1.amazonaws.com
          dockerfile: Dockerfile
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

